server:
  port: 7001

spring:
  application:
    name: HOTEL-INVENTORY-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Root@001
    url: jdbc:mysql://localhost:3306/hotel_inventory
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
  config:
    import: configserver:http://localhost:8001
